### ISSUE TITLE
Installation fails on OP1

### ISSUE THREAD

**Issue by srgbpnkru** [NorthernMan54/homebridge-wssensor#7]
Sorry, but I can't figure out what's going on here. I'm still a beginner, so I don't really understand these. When I tried to install your plug-in I've got the following:
```
root@orangepione:~# sudo npm install -g homebridge-wssensor

> mdns@2.4.0 install /usr/local/lib/node_modules/homebridge-wssensor/node_modules/mdns
> node-gyp rebuild

gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 4.19.38-sunxi
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-wssensor/node_modules/mdns
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-30T15_58_33_146Z-debug.log
```
I've tried to install node-gyp with `sudo npm install -g node-gyp` and it went ok:
```
root@orangepione:~# sudo npm install -g node-gyp
/usr/local/bin/node-gyp -> /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
+ node-gyp@4.0.0
updated 6 packages in 15.729s
```
But `sudo npm install -g homebridge-wssensor` still fails. I've tried the same without the `-g` flag, it did install but didn't work: Homebridge says the following on startup:
```
Error: The requested platform 'wssensor' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3) 
```
And this is `sudo npm install homebridge-wssensor` without the `-g` flag.
```
root@orangepione:~# sudo npm install homebridge-wssensor

> mdns@2.4.0 install /root/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/root/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_browse.o
../src/dns_service_browse.cpp: In function 'void node_mdns::OnServiceChanged(DNSServiceRef, DNSServiceFlags, uint32_t, DNSServiceErrorType, const char*, const char*, const char*, void*)':
../src/dns_service_browse.cpp:39:50: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
     Nan::MakeCallback(this_, callback, argc, info);
                                                  ^
In file included from ../src/mdns.hpp:12:0,
                 from ../src/dns_service_browse.cpp:1:
../../nan/nan.h:1024:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_enumerate_domains.o
../src/dns_service_enumerate_domains.cpp: In function 'void node_mdns::OnEnumeration(DNSServiceRef, DNSServiceFlags, uint32_t, DNSServiceErrorType, const char*, void*)':
../src/dns_service_enumerate_domains.cpp:29:50: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
     Nan::MakeCallback(this_, callback, argc, info);
                                                  ^
In file included from ../src/mdns.hpp:12:0,
                 from ../src/dns_service_enumerate_domains.cpp:1:
../../nan/nan.h:1024:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_get_addr_info.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_process_result.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_sock_fd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_register.o
../src/dns_service_register.cpp: In function 'void node_mdns::OnServiceRegistered(DNSServiceRef, DNSServiceFlags, DNSServiceErrorType, const char*, const char*, const char*, void*)':
../src/dns_service_register.cpp:48:54: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
         Nan::MakeCallback(this_, callback, argc, info);
                                                      ^
In file included from ../src/mdns.hpp:12:0,
                 from ../src/dns_service_register.cpp:1:
../../nan/nan.h:1024:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_resolve.o
../src/dns_service_resolve.cpp: In function 'void node_mdns::OnResolve(DNSServiceRef, DNSServiceFlags, uint32_t, DNSServiceErrorType, const char*, const char*, uint16_t, uint16_t, const unsigned char*, void*)':
../src/dns_service_resolve.cpp:51:50: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
     Nan::MakeCallback(this_, callback, argc, info);
                                                  ^
In file included from ../src/mdns.hpp:12:0,
                 from ../src/dns_service_resolve.cpp:1:
../../nan/nan.h:1024:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_update_record.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/mdns_utils.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/network_interface.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/socket_watcher.o
../src/socket_watcher.cpp: In static member function 'static void node_mdns::SocketWatcher::Callback(uv_poll_t*, int, int)':
../src/socket_watcher.cpp:100:63: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
         Nan::MakeCallback(watcher->handle(), callback, 2, argv);
                                                               ^
In file included from ../src/mdns.hpp:12:0,
                 from ../src/socket_watcher.cpp:1:
../../nan/nan.h:1024:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_create.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_set_value.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_get_length.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_buffer_to_object.o
  SOLINK_MODULE(target) Release/obj.target/dns_sd_bindings.node
  COPY Release/dns_sd_bindings.node
make: Leaving directory '/root/node_modules/mdns/build'
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

+ homebridge-wssensor@0.1.42
added 68 packages from 82 contributors and audited 1045 packages in 197.833s
found 0 vulnerabilities
```
Did I mess something up? Maybe you have any clue on what's going on...

My setup is **Orange Pi One** 
with **ARMBIAN 5.85 stable Ubuntu 18.04.2 LTS 4.19.38-sunxi.**

NPM is version **6.9.0** and Node.js is version **8.10.0**.

I can confirm that Homebridge is working as expected. It has two plugins installed and working: **homebridge-cmd_light_control** and **homebridge-cmdswitch2**. 

I really appreciate any help you can provide.

**Comment by NorthernMan54** [comment]
Looking at this, you have installed the plugin twice, in two different locations which is really going to make it hard to troubleshoot.  One copy appears to be in

`/usr/local/lib/node_modules/homebridge-wssensor`

And the second

`/root/`

This is a result of installing with and without the -g flag as root

I would recommend retrying with -g option, I wondering if that will work now that you have installed node-gyp?

Btw, what type of nodemcu sensor are you planning to deploy?

**Comment by srgbpnkru** [comment]
Hm, I believe it did install once, to the `/root/` folder. I've tried to install with `-g` flag after updating node-gyp, but with no avail. 
But, when I'm trying to install it from the `/root/node_modules` with `-g` flag it succeeds and creates a symlink folder `/homebridge-wssensor` with some warnings though. 
There is always something with **mdns**. Maybe this is the key to the problem?
```
root@orangepione:~/node_modules# sudo npm install -g homebridge-wssensor
npm WARN lifecycle mdns@2.4.0~install: cannot run in wd mdns@2.4.0 node-gyp rebuild (wd=/root/node_modules/homebridge-wssensor/node_modules/mdns)
+ homebridge-wssensor@0.1.42
added 116 packages from 135 contributors in 37.932s
```

As of now it can't load the plugin and therefore fails on platform load as well:
```
root@orangepione:~/node_modules# homebridge
[5/31/2019, 7:00:54 PM] Loaded config.json with 1 accessories and 1 platforms.
[5/31/2019, 7:00:54 PM] ---
[5/31/2019, 7:00:54 PM] Loaded plugin: homebridge-cmd_light_control
[5/31/2019, 7:00:54 PM] Registering accessory 'homebridge-cmd.CMD'
[5/31/2019, 7:00:54 PM] ---
[5/31/2019, 7:00:55 PM] Loaded plugin: homebridge-cmdswitch2
[5/31/2019, 7:00:55 PM] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[5/31/2019, 7:00:55 PM] ---
[5/31/2019, 7:00:56 PM] ====================
[5/31/2019, 7:00:56 PM] ERROR LOADING PLUGIN homebridge-wssensor:
[5/31/2019, 7:00:56 PM] Error: /root/node_modules/homebridge-wssensor/node_modules/mdns/build/Release/dns_sd_bindings.node: invalid ELF header
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/node_modules/homebridge-wssensor/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
[5/31/2019, 7:00:56 PM] ====================
[5/31/2019, 7:00:56 PM] Loading 1 platforms...
[5/31/2019, 7:00:56 PM] Error: The requested platform 'wssensor' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
[5/31/2019, 7:00:57 PM] Got SIGTERM, shutting down Homebridge...
```
I don't know... I'm starting to think that this is not related to your plugin but to my whole setup. Must be something with this **mdns**. I should look further into this way.

I've bought an NodeMCU v.3 Lolin and the sensor is AM312, the exact one you've used I believe.

**Comment by srgbpnkru** [comment]
https://github.com/nfarina/homebridge/issues/914#issuecomment-332477679

I've found these, looks exactly like my issue. But what do they mean by "configuring my linux distro correctly"?

**Comment by srgbpnkru** [comment]
Hi, any updates?

**Comment by NorthernMan54** [comment]
Did you get the plugin installed?

**Comment by srgbpnkru** [comment]
Yep, I did! `--unsafe-perm` flag did the trick I believe.
